# Site settings
title: code-for-coffee's portfolio
email: jtraverjr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The online portfolio of code-for-coffee
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://code-for-coffee.github.io" # the base hostname & protocol for your site
twitter_username: code4coffee
github_username:  code-for-coffee

# Build settings
markdown: kramdown
